version: '2'
services:
    test:
        build: .
        command: npm run test
        volumes:
        - .:/usr/app/
        - /usr/app/node_modules
        links:
        - postgres
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_USER: test
            POSTGRES_DB: test
            POSTGRES_PASSWORD: test
    postgres:
        image: postgres:9.6.2-alpine
        ports:
        - "8990:5432"
        environment:
            POSTGRES_USER: test
            POSTGRES_DB: test
            POSTGRES_PASSWORD: test
